
services:
  postgres:
    image: postgres:16-alpine
    container_name: yuriana_db
    restart: always
    env_file:
      - .env
    environment:
      # MAPEAMOS CON TUS NUEVAS VARIABLES DEL .ENV
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - red_yuriana
    healthcheck:
      # El chequeo de salud ahora usará tus nuevas credenciales
      test: ["CMD-SHELL", "pg_isready -U $${DATABASE_USER} -d $${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: yuriana_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - red_yuriana

  frontend:
    container_name: yuriana_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    command: npm run dev
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - red_yuriana

volumes:
  postgres_data:

networks:
  red_yuriana: