services:
  postgres:
    image: postgres:16-alpine
    container_name: yuriana_db_prod
    restart: always
    env_file:
      - .env
    environment:
      TZ: America/La_Paz
      PGTZ: America/La_Paz
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data  # Volumen persistente puro
    networks:
      - red_yuriana_prod

  backend:
    container_name: yuriana_backend_prod
    build:
      context: ./backend
      dockerfile: Dockerfile  # Tu Dockerfile aquí adentro debe hacer el 'npm run build' e iniciar con 'npm run start:prod'
    restart: always
    env_file:
      - .env
    environment:
      TZ: America/La_Paz
      NODE_ENV: production
    depends_on:
      - postgres
    networks:
      - red_yuriana_prod

  frontend:
    container_name: yuriana_frontend_prod
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Tu Dockerfile aquí adentro debe hacer el 'next build' e iniciar con 'next start'
    restart: always
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    networks:
      - red_yuriana_prod

volumes:
  postgres_data_prod:

networks:
  red_yuriana_prod: